version: '3.8'

services:

  db:
    image: postgres:15.2
    container_name: email-test
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=email-test
      - POSTGRES_USER=rrojas
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"