#DATABASE
POSTGRES_SQL_USERNAME: rrojas
POSTGRES_SQL_PASSWORD: 123456789
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: email-test

#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: lucras015@gmail.com
EMAIL_PASSWORD: qbuw pbsf zprl ezan
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}